language: python
sudo: required
dist: trusty
python:
  - "2.7"
install:
  - "pip install tox-travis"
  - "pip install setuptools-markdown"
script: tox
before_deploy:
  - "rm -rf dist"
  - "./scripts/pkg.sh"
deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - dist/snap-plugin-collector-diamond/linux/x86_64/snap-plugin-collector-diamond-linux-x86_64.aci
    skip_cleanup: true
    on:
      repo: mkleina/snap-plugin-collector-diamond
      tags: true
