language: python
sudo: required
dist: trusty
python:
  - "2.7"
before_install:
  - sudo ln -s $TRAVIS_BUILD_DIR/.tox/py27/share/diamond /usr/share/diamond
install:
  - "pip install tox-travis"
  - "pip install setuptools-markdown"
script: tox
before_deploy:
  - "rm -rf dist"
  - "./scripts/pkg.sh"
deploy:
  - provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: snap.ci.snap-telemetry.io
    region: us-west-2
    skip_cleanup: true
    local-dir: dist
    upload-dir: plugins
    acl: public_read
    on:
      repo: intelsdi-x/snap-plugin-collector-pysmart
      tags: true
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://pypi.python.org/pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    on:
      tags: true
      repo: intelsdi-x/snap-plugin-collector-pysmart
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - dist/snap-plugin-collector-diamond/linux/x86_64/snap-plugin-collector-diamond-linux-x86_64.aci
    skip_cleanup: true
    on:
      repo: intelsdi-x/snap-plugin-collector-diamond
      tags: true
